---
title: "BIRDIE: South Africa's Data Pipeline for Wetlands and Waterbirds"
author: "Francisco Cervantes, Yvan Stojanov, Francis Strobbe, Michael Brooks and Res Altwegg"
date: "`r format(Sys.Date(), '%d %B %Y')`"
subtitle: 'International Ornithological Congress 2022'
output: pdf_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../output") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Abstract

Waterbirds often server as indicators and flagship species for wetland conservation. With wetlands playing a key role in reversing the alarming trends in biodiversity loss and climate change, it is imperative that efficient monitoring of wetlands and waterbirds is in place. In turn, this requires data collection at large scale, and robust analytical routines to process these data into meaningful indicators. Citizen science programmes are considered a potential solution to large scale data collection, while data pipelines offer a solution for streamlined analysis and indicator production.

The South Africa’s Data Pipeline for Wetlands and Waterbirds (BIRDIE) uses data collected by two long-term country-wide citizen-science projects: the Coordinated Waterbird Counts and the Southern African Bird Atlas Project. BIRDIE leverages these datasets, as well as other opportunistic records, to understand the distribution and population dynamics of waterbird species. Within the BIRDIE project, these citizen-science data are vetted, validated and analysed using a suite of statistical techniques to arrive at decision-relevant outputs that are made available on an online dashboard.

The project is still under development and we hope it will soon contribute to waterbird and wetland conservation at multiple scales; from international programmes, such as Ramsar or the Agreement on the Conservation of African-Eurasian Migratory Waterbirds, to National Biodiversity Assessments and local site management.

