---
title: "BIRDIE: A datapipeline to inform wetland and waterbird conservation at multiple scales"
runtitle: "BIRDIE Biodiversity Datapipeline"
documentclass: frontiersSCNS  # or frontiersHLTH, or frontiersFPHY
author:
  - name: Francisco Cervantes
    affiliation: '1,2'
    etal: Cervantes # First author's last name.
    email: f.cervantesperalta@gmail.com # Indicates corresponding Author
    institution: University of Cape Town
    street: Rondebosch
    city: Cape Town
    state: State XX # only USA, Australia, Canada
    zip: 7700
    country: South Africa
  - name: Francis Strobbe
    affiliation: '3'
  - name: Yvan Stojanov
    affiliation: '3'
  - name: Michael Brooks
    affiliation: '4'
  - name: Vernon Visser
    affiliation: '1'
  - name: Andrew Skowno
    affiliation: '2'
  - name: Nancy Job
    affiliation: '2'
  - name: Res Altwegg
    affiliation: '1'
affiliation:
  - id: '1'
    department: Centre for Statistics in Ecology, the Environment and Conservation
    institution: University of Cape Town
    city: Cape Town
    country: South Africa
  - id: '2' 
    department: South African National Biodiversity Institute
    institution: Kirstenbosch Research Centre
    city: Cape Town
    country: South Africa
  - id: '3' 
    department: Operational Directorate Natural Environment
    institution: Royal Belgian Institute of Natural Sciences
    city: Brussels
    country: Belgium
  - id: '4'
    department: FitzPatrick Institute of African Ornithology
    institution: University of Cape Town
    city: Cape Town
    country: South Africa
output: rticles::frontiers_article
csl: frontiers.csl
bibliography: test.bib
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../output") })
---

\begin{abstract}

1000 words max

With increasing pressure on Earth’s ecosystems, we have seen substantial efforts in the collection  and management of ecological and environmental data, over the last decade. This is especially true for freshwater ecosystems, which are amongst the most impacted by human activity, and yet they have been lagging behind in terms of data availability, compared to other terrestrial ecosystems. Despite improvements in data collection and accessibility, raw data still need to be analyzed and interrogated to support conservation programmes and management decisions; a process that can be complex and time consuming. The South African Biodiversity Data Pipeline for Wetlands and Waterbirds (BIRDIE) aims at helping fast and efficient information uptake, bridging the gap between raw ecological datasets and final users. BIRDIE will be an online portal that will not only serve ecological data, but also implement analytical routines to process these data and produce policy-relevant indicators. The project focuses on waterbirds and their utility as proxy indicators of wetland condition. We use two citizen-science bird monitoring datasets to assess the state of waterbird populations in South Africa, namely: the African Bird Atlas Project and the Coordinated Waterbird Counts. In addition, a suite of environmental layers help link waterbird populations with the state of the associated wetlands. Acknowledging that conservation programmes run at multiple scales, from site management to international agreements, we have developed a granular framework in which waterbird population indicators are estimated at small scales, and then these are aggregated to compute the similar indicators at broader scales.

Data pipeline tasks are organized in multiple blocks that can be run independently, which gives the pipeline an easy to manage, modular structure. Blocks include routines, such as: occupancy modeling, state-space modeling, and computation of indicators associated with waterbird distribution, abundance or diversity. BIRDIE will provide free access to these indicators on an online dashboard that will go live next year, and that will be updated regularly, as new data arrive. The dashboard is designed to provide spatial and temporal visualization of the indicators using maps and time series, to help contextualization. This paper describes the structure of the BIRDIE pipeline and the technical features underpinning its components.


\end{abstract}

