---
title: "South African Biodiversity Data Pipeline for Wetlands and Waterbirds (BIRDIE)"
author: "Francisco Cervantes"
date: "07/07/2021"
subtitle: 'National Wetlands Indaba 2021'
output: pdf_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../output") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Abstract

With ever-increasing pressure on wetlands due to the scarcity of freshwater on Earth, there is an urgent need to monitor the status of these ecosystems. In this context, waterbirds often serve as flagship and indicator species for other less accessible ecological riches. In this talk, we will learn about the South African Biodiversity Data Pipeline for Wetlands and Waterbirds, affectively named BIRDIE. This project emerges from a collaboration between multiple organizations, with the overarching objective of serving as a link between South African nation-wide waterbird data collection programmes and conservation managers, researchers and other stakeholders. More precisely, the project will use data from the Coordinated Waterbird Counts and the Southern African Bird Atlas Project to understand the distribution and population dynamics of waterbird species. These citizen-science data will be processed with rigorous statistical analysis to gain insights about these processes that raw data might not reveal. The information will then be made available on an online platform. The project will contribute to the implementation of international programmes, such as the RAMSAR convention, the Agreement on the Conservation of African-Eurasian Migratory Waterbirds, and the Convention on Biological Diversity. At a national level, the outputs from BIRDIE will contribute to red-listing assessments, National Biodiversity Assessments, as well as to support site management and decision making. Hopefully, these outputs will also generate new interesting research questions. In the future, we hope to see BIRDIE expand to other regions and integrate with other biodiversity portals to promote a better understanding of the interactions between different taxonomic groups associated to wetlands.
