---
title: "SABAP: An R package to access African Bird Atlas data"
author: "Francisco Cervantes, Michael Brooks and Res Altwegg"
date: "`r format(Sys.Date(), '%d %B %Y')`"
subtitle: 'International Statistical Ecology Conference 2022'
output: pdf_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../output") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Abstract

The Southern African Bird Atlas Project 2(SABAP2) is one of the largest and most important biodiversity monitoring projects in southern Africa. SABAP2 (2007-ongoing) is a follow up to the SABAP1 project (1987-1992). The protocol developed in SABAP2 project has been rolled out across Africa through the African Bird Atlas Project (ABAP), using a single atlasing protocol and set of tools that can be applied across the continent. ABAP holds over 19.4 million bird observation records collected across the continent, with the majority of these records fall into the SABAP2 region (South Africa, Lesotho, eSwatini, Namibia, Botswana, Zimbabwe, Zambia and Mozambique), Kenya BirdMap and the Nigerian Bird Atlas Project. (http://www.birdmap.africa/) 

SABAP2/ABAP has developed a suite of API calls to facilitate easier data access for users. These API calls allow users to access raw and summarised data directly from the database for analysis in their chosen platforms. To extend these API calls, and making data integration and analysis using R more efficient, we have created SABAP, an R package that connects to the SABAP2/ABAP API, allowing R to access data directly and removing any unecessary steps in the process. These data integrates seamlessly into workflows using trending R formats such as `tibble` or the spatial `sf`. In addition, the package offers the possibility to annotate SABAP2/ABAP observations with Google Earth Engine environmental data, facilitating the flexibility and reproducibility of the analyses.
