---
title: "South African Biodiversity Data Pipeline for Wetlands and Waterbirds (BIRDIE)"
author: "Francisco Cervantes"
date: "`r format(Sys.Date(), '%d %B %Y')`"
subtitle: 'International Statistical Ecology Conference 2022'
output: pdf_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../output") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Abstract

With ever-increasing pressure on wetlands due to the scarcity of freshwater on Earth, there is an urgent need to monitor the status of these ecosystems. In this context, waterbirds often serve as flagship and indicator species for other less accessible ecological riches. The South African Biodiversity Data Pipeline for Wetlands and Waterbirds (BIRDIE) emerges from a collaboration between multiple organizations, with the overarching objective of serving as a link between South African nation-wide waterbird data collection programmes and conservation managers, researchers and other stakeholders.

In South Africa, there are two country-wide citizen-science projects that provide waterbird data: the Coordinated Waterbird Counts and the Southern African Bird Atlas Project. BIRDIE will leverage data from both datasets, and other sources, to understand the distribution and population dynamics of waterbird species. Behind the scenes, these citizen-science data will be analyzed using a suite of techniques, such as state-space models and occupancy models to estimate population dynamics and distributions. The results will be made available on an online dashboard.

The project will contribute to the implementation of international programmes, such as the RAMSAR convention, the Agreement on the Conservation of African-Eurasian Migratory Waterbirds, and the Convention on Biological Diversity. At a national level, the outputs from BIRDIE will contribute to Red-Listing assessments, National Biodiversity Assessments, as well as to support site management and decision making. Designing a data pipeline that fits more than two hundred species and that runs automatically poses many challenges. In this talk, we will know about the goals of this project, the structure of the pipeline, and some of the challenges met so far.

