---
title: "ABAP: An R package to access African Bird Atlas data"
author: "Francisco Cervantes, Michael Brooks and Res Altwegg"
date: "`r format(Sys.Date(), '%d %B %Y')`"
subtitle: 'International Statistical Ecology Conference 2022'
output: pdf_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../output") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Abstract

The Southern African Bird Atlas Project 2 (SABAP2) is one of the largest and most important biodiversity monitoring projects in southern Africa. SABAP2 (2007-ongoing) is a follow up to the SABAP1 project (1987-1992). The protocol developed for SABAP2 has been rolled out to multiple African countries, through the African Bird Atlas Project (ABAP), using a single atlasing protocol and set of tools that can be applied across the continent. ABAP holds over 19.4 million bird observation records, with the majority of these records falling into the SABAP2 region (South Africa, Lesotho, eSwatini, Namibia, Botswana, Zimbabwe, Zambia and Mozambique), Kenya BirdMap and the Nigerian Bird Atlas Projects (http://www.birdmap.africa/).

ABAP has developed a suite of API calls to facilitate easier data access for users. These API calls allow users to access raw and summarised data directly from the database for analysis in their chosen platforms. To extend these API calls, and facilitate integration with the R environment, we have created ABAP, an R package that connects to the ABAP API, allowing R to access data directly, removing any unnecessary intermediate steps. These data integrate seamlessly into workflows using trending R formats such as `tibble` or the spatial `sf`. In addition, the package offers the possibility to annotate ABAP observations with Google Earth Engine environmental data, facilitating the flexibility and reproducibility of the analyses.
