---
title: "SABAP: An R package to access African Bird Atlas data"
author: "Francisco Cervantes, Michael Brooks and Res Altwegg"
date: "`r format(Sys.Date(), '%d %B %Y')`"
subtitle: 'International Statistical Ecology Conference 2022'
output: pdf_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../output") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Abstract

The Southern African Bird Atlas Project 2(SABAP2) is one of the longest lasting and most important biodiversity monitoring projects in Africa. A folow up to the SABAP1 project (1987-1992), SABAP2 (2007-ongoing) has collected over 18 million records to the dataset. At present, approximatley two million bird observations records are added by citizen scientists per year. The BirdMap protocol developed in SABAP2 project has been rolled out to multiple African countries including Kenya and Nigeria, and  has motivated the creation of the African Bird Atlas, using a single atlasing protocol and set of tools that can be applied across the continent. 

SABAP2/BirdMap has developed a suite of API calls to facilitate easier data access for users. These API calls allow users to access raw and summarised data directly from the database for analysis in their chosen platforms. To extend these API calls, and making data integration and analysis using R more efficient, we have created SABAP, an R package that connects to the SABAP2/BirdMap API, allowing R to access data directly and removing any unecessary steps in the process. These data integrates seamlessly into workflows using trending R formats such as `tibble` or the spatial `sf`. In addition, the package offers the possibility to annotate SABAP2/BirdMap observations with Google Earth Engine environmental data, facilitating the flexibility and reproducibility of the analyses.
