---
title: "Delivering policy-relevant information: a Data Pipeline for Waterbirds in South Africa"
author: "Francisco Cervantes, Francis Strobbe, Michael Brooks and Res Altwegg"
date: "`r format(Sys.Date(), '%d %B %Y')`"
subtitle: 'International Statistical Ecology Conference 2022'
output: pdf_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../output") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Abstract

As ecology has entered the age of big data, raw data on ecosystems are becoming increasingly readily available. The next challenge is for decision makers to extract relevant information from these data. We are developing a data pipeline that starts with raw data submitted by citizen scientists, vets the data for internal consistency, statistically analyses the data and makes decision-relevant outputs available via an online dashboard.

With ever-increasing pressure on wetlands due to the scarcity of freshwater on Earth, there is an urgent need to monitor the status of these ecosystems. In this context, waterbirds often serve as flagship and indicator species for other less accessible taxa. In South Africa, there are two country-wide citizen-science projects that provide waterbird data: the Coordinated Waterbird Counts and the Southern African Bird Atlas Project. The South African Biodiversity Data Pipeline for Wetlands and Waterbirds (BIRDIE) emerges from a collaboration between multiple organizations, with the overarching objective of leveraging these datasets and present useful indicators to conservation managers, researchers and other stakeholders.

BIRDIE will leverage the aforementioned datasets, as well as other opportunistic records, to understand the distribution and population dynamics of waterbird species. Behind the scenes, these citizen-science data are analyzed using a suite of statistical techniques, such as state-space, and occupancy models to estimate population dynamics and distributions. The results will be made available via an online dashboard, and via an API for system integration.

The project will contribute to the implementation of international programmes, such as the RAMSAR convention, the Agreement on the Conservation of African-Eurasian Migratory Waterbirds, and the Convention on Biological Diversity. At a national level, the outputs from BIRDIE will contribute to Red-Listing assessments, National Biodiversity Assessments, as well as to support site management and decision making. Designing a data pipeline that fits more than two hundred species and that runs automatically poses many challenges. We show that including sophisticated statistical analyses into data pipelines is possible and demonstrate the value the add for decision makers.

<!--In this talk, we will know about the goals of this project, the structure of the pipeline, and some of the challenges met so far.-->

