#' Fit state-space JAGS model
#'
#' @param counts A data frame with counts generated by \code{\link{ppl_create_data_ssm}}
#' @param sp_code SAFRING code of the species of interest
#' @inheritParams ppl_run_pipe_abu1
#'
#' @return
#' @export
#'
#' @examples
ppl_fit_ssm_model <- function(counts, sp_code, config, ...){

    # Create covariate matrix for mean population change
    covts_u <- counts %>%
        dplyr::filter(season_id == 1) %>%
        dplyr::rename_with(~gsub("_mean||_count", "", .x), .cols = dplyr::everything()) %>%
        dplyr::select(site_id, year_id, pdsi, watrec) %>%
        dplyr::mutate(dplyr::across(.cols = c(pdsi, watrec), .fns = ~scale(.x)))

    # # add intercept
    # covts_u <- covts_u %>%
    #     dplyr::mutate(intcp = 1) %>%
    #     dplyr::select(intcp, dplyr::everything())

    # Convert to array of multiple sites
    U <- covts_u %>%
        dplyr::select(-year_id) %>%
        dplyr::nest_by(site_id) %>%
        dplyr::pull(data) %>%
        unlist() %>%
        array(., dim = c(dplyr::n_distinct(counts$year_id),
                         ncol(covts_u) - 2, # this removes year and site columns
                         dplyr::n_distinct(counts$site_id)))

    # Add one to all counts so that we can take logs
    counts <- counts %>%
        dplyr::mutate(count = count + 1)

    # Scale response so that all sites are similar
    sc_site <- counts %>%
        dplyr::group_by(site_id) %>%
        dplyr::summarise(sd_count = stats::sd(count, na.rm = TRUE)) %>%
        dplyr::pull(sd_count)

    counts <- counts %>%
        dplyr::group_by(site_id) %>%
        dplyr::mutate(sd_count = stats::sd(count, na.rm = TRUE)) %>%
        dplyr::ungroup() %>%
        dplyr::mutate(count = count / sd_count)

    # Find median count to pass it as the initial population estimate
    ini_count <- counts %>%
        dplyr::filter(season_id == 1) %>%
        dplyr::mutate(count = log(count)) %>%
        dplyr::group_by(site_id) %>%
        dplyr::summarise(meds = dplyr::first(count, na_rm = TRUE),
                         precs = 1/stats::var(count, na.rm = TRUE))

    # Mean winter to summer ratio
    ini_ws <- counts %>%
        dplyr::group_by(site_id, year, Season) %>%
        dplyr::summarise(count = mean(count, na.rm = TRUE)) %>%
        tidyr::pivot_wider(names_from = "Season", values_from = "count") %>%
        dplyr::mutate(ws = log(W/S)) %>%
        dplyr::group_by(site_id) %>%
        dplyr::summarise(meds = dplyr::first(ws, na_rm = TRUE),
                         precs = 1/stats::var(ws, na.rm = TRUE))

    # Non-missing data indices
    obs_idx <- which(!is.na(counts$count))
    N_data_obs <- length(obs_idx)

    # Prepare data
    data <- list(
        med_log_count = ini_count$meds,
        prec_log_count = ini_count$precs,
        med_ws = ini_ws$meds,
        prec_ws = ini_ws$precs*2,
        count = log(counts$count), # NOTE WE ADDED ONE TO AVOID ZERO COUNTS AND NON-IDENTIFIBILITY OF PARAMETERS
        summer = dplyr::case_when(counts$season_id == 1 ~ 1L,
                                  counts$season_id == 2 ~ 0L,
                                  TRUE ~ NA_integer_),
        nyears = dplyr::n_distinct(counts$year_id),
        nsites = dplyr::n_distinct(counts$site_id),
        year = counts$year_id,
        site = counts$site_id,
        N = nrow(counts),
        U = U,
        M = ncol(U),
        obs_idx = obs_idx,
        N_data_obs = N_data_obs,
        sc_site = sc_site
    )

    # Set initial values
    inits <- function(){
        list(mu_ini = runif(data$nsites, 0, 10),
             beta_ini = rnorm(data$nsites, 0, 3),
             lambda_ini = rnorm(data$nsites, 0, 3),
             tau.alpha = rexp(data$nsites, 0.5),
             tau.e = rexp(data$nsites, 0.5),
             G = matrix(rnorm(data$M * data$nsites, 0, 1), ncol = data$M),
             mu_g = rnorm(data$M, 0, 0.5),
             sig_g = rexp(data$M, 1),
             tau.eps = rexp(data$nsites, 1),
             tau.zeta = rexp(data$nsites, 1),
             phi = runif(data$nsites, 0.2, 0.8),
             psi_s_sc0 = rexp(data$nsites, 1),
             psi_w_sc0 = rexp(data$nsites, 1)
             )
    }

    param = c("beta", "lambda", "sig.zeta", "sig.eps", "sig.alpha", "sig.e", "stt_s", "stt_w", "phi", "psi_s", "psi_w", "pj", "tau.jump", "log.lik")
    # param = c("beta", "lambda", "sig.zeta", "sig.eps", "sig.alpha", "sig.e", "stt_s", "stt_w", "phi", "psi_s", "psi_w", "mu_g", "sig_g", "pj", "tau.jump", "log.lik")
    # param = c("beta", "lambda", "r", "sig.zeta", "sig.eps", "sig.alpha", "sig.e", "stt_s", "stt_w", "psi_s", "psi_w", "log.lik")

    print(paste("Fitting state-space JAGS model at", Sys.time()))

    # Fit 2-season dynamic trend model
    fit <- jagsUI::jags.basic(data = data,
                              parameters.to.save = param,
                              model.file = file.path(config$mod_dir, config$mod_file),
                              inits = inits,
                              n.chains = 3, n.iter = 20000, n.burnin = 10000, n.thin = 10,
                              modules = c('bugs', 'glm', 'dic'), parallel = TRUE,
                              n.cores = 3, DIC = TRUE, verbose = TRUE)

    return(fit)

}
