#' Fit state-space JAGS model
#'
#' @param counts A data frame with counts generated by \link{\code{ppl_create_data_ssm}}
#' @param sp_code SAFRING code of the species of interest
#' @inheritParams ppl_run_pipe_abu1
#'
#' @return
#' @export
#'
#' @examples
ppl_fit_ssm_model <- function(counts, sp_code, config, ...){

    # Create covariate matrix for mean population change
    covts_u <- counts %>%
        dplyr::filter(season_id == 1) %>%
        dplyr::rename_with(~gsub("_mean||_count", "", .x), .cols = dplyr::everything()) %>%
        dplyr::select(site_id, year_id, pdsi, watext, watrec) %>%
        dplyr::mutate(dplyr::across(.cols = c(pdsi, watext, watrec), .fns = ~scale(.x)))

    # add intercept
    covts_u <- covts_u %>%
        dplyr::mutate(intcp = 1) %>%
        dplyr::select(intcp, dplyr::everything())

    # Convert to array of multiple sites
    U <- covts_u %>%
        dplyr::select(-year_id) %>%
        dplyr::nest_by(site_id) %>%
        dplyr::pull(data) %>%
        unlist() %>%
        array(., dim = c(dplyr::n_distinct(counts$year_id),
                         ncol(covts_u) - 2, # this removes year and site columns
                         dplyr::n_distinct(counts$site_id)))

    # Prepare data
    data <- list(
        count = counts$count + 1, # NOTE THE PLUS ONE TO AVOID ZERO COUNTS AND NON-IDENTIFIBILITY OF PARAMETERS
        summer = dplyr::case_when(counts$season_id == 1 ~ 1L,
                                  counts$season_id == 2 ~ 0L,
                                  TRUE ~ NA_integer_),
        nyears = dplyr::n_distinct(counts$year_id),
        nsites = dplyr::n_distinct(counts$site_id),
        year = counts$year_id,
        site = counts$site_id,
        N = nrow(counts),
        U = U,
        M = ncol(U))

    # Set initial values
    inits <- function(){
        list(zeta_ini = rnorm(data$nsites, 0, 1),
             lambda_ini = rnorm(data$nsites, 0, 1),
             tau.alpha = rgamma(data$nsites, 3, 2),
             tau.e = rgamma(data$nsites, 3, 2),
             G = matrix(rnorm(data$M * data$nsites, 0, 1), ncol = data$M),
             mu_g = rnorm(data$M, 0, 0.5),
             sig_g = rexp(data$M, 1),
             tau.eps = rexp(data$nsites, 1),
             tau.zeta = rexp(data$nsites, 1),
             phi.mu = runif(data$nsites, 0.2, 0.8))
    }

    param = c("beta", "lambda", "sig.zeta", "sig.eps", "sig.alpha", "sig.e", "stt_s", "stt_w", "summer", "phi.mu")

    # param = c("beta", "mu.beta", "B", "G", "mu_t")

    print(paste("Fitting state-space JAGS model at", Sys.time()))

    # Fit 2-season dynamic trend model
    fit <- jagsUI::jags.basic(data = data,
                              parameters.to.save = param,
                              model.file = file.path(config$mod_dir, config$mod_file),
                              inits = inits,
                              n.chains = 3, n.iter = 10000, n.burnin = 5000,
                              modules = c('glm', 'dic'), parallel = TRUE,
                              n.cores = 3, DIC = TRUE, verbose = TRUE)

    return(fit)

}
