#' Summarise predictions from state-space JAGS model
#'
#' @param fit A model fit generated by \link{\code{ppl_fit_ssm_model}}
#' @param counts A data frame with counts generated by \link{\code{ppl_create_data_ssm}}
#' @param sp_code SAFRING code of the species of interest
#' @inheritParams ppl_run_pipe_abu1
#'
#' @return
#' @export
#'
#' @examples
ppl_summarise_ssm <- function(fit, counts, sp_code, config, ...){

    message(paste("Summarizing state-space JAGS model at", Sys.time()))

    fit_stats <- BIRDIE:::processJAGSoutput(fit, DIC = FALSE, params.omit = NULL)

    message("Generating plots and tables")

    # Plot
    pers_theme <- ggplot2::theme_bw()
    p <- BIRDIE::plotJagsSsm2ss(fit = fit_stats, ssm_counts = counts, linear = TRUE,
                                plot_options = list(pers_theme = pers_theme,
                                                    colors = c("#71BD5E", "#B590C7")))

    # grid::grid.newpage()
    # grid::grid.draw(p$plot)

    out_all_sites <- vector("list", length(unique(counts$LocationCode)))

    for(i in seq_along(out_all_sites)){

        site_sel <- names(p)[[i]]

        plotdir <- setSpOutFilePath("ssm_plot", config, sp_code, paste0("_", site_sel, ".png"))

        ggplot2::ggsave(plotdir, plot = p[[i]]$plot, width = 6.4, height = 5.2)

        # Extract plot data
        plotdata <- p[[i]]$data

        # Prepare state data
        stt_df <- plotdata[[1]]

        stt_df <- stt_df %>%
            tidyr::pivot_wider(names_from = "quantile", values_from = "value")

        stt_dfw <- cbind(stt_df %>%
                             dplyr::filter(season == "summer") %>%
                             dplyr::select(-c(site_id, season)),
                         stt_df %>%
                             dplyr::filter(season == "winter") %>%
                             dplyr::select(-c(site_id, year, season, loc_code)))

        names(stt_dfw) <- c("year", "site", "summer.count", "summer.est", "summer.ci.lower", "summer.ci.upper",
                            "winter.count", "winter.est", "winter.ci.lower", "winter.ci.upper")

        # Prepare trend data
        trd_df <- plotdata[[2]]

        names(trd_df) <- c("slope.est", "slope.ci.lower", "slope.ci.upper",
                           "winter.prop.est", "winter.prop.ci.lower", "winter.prop.ci.upper",
                           "year")

        # Combine
        out_df <- cbind(stt_dfw, dplyr::select(trd_df, -year))

        # Add missing columns
        out_df <- out_df %>%
            dplyr::mutate(species = sp_code)#,
        # summer.count = round(exp(log.summer.count)),
        # winter.count = round(exp(log.winter.count)))

        # Order columns
        out_df <- out_df %>%
            dplyr::select(species, site, year, summer.count, winter.count,
                          summer.est, winter.est, winter.ci.lower,
                          winter.ci.upper,
                          summer.ci.lower, summer.ci.upper,
                          slope.est, slope.ci.lower, slope.ci.upper,
                          winter.prop.est, winter.prop.ci.lower,
                          winter.prop.ci.upper)

        out_all_sites[[i]] <- out_df

    }

    out_all_sites <- dplyr::bind_rows(out_all_sites)

    return(out_all_sites)

}
