#'
#' Fit occupancy models in parallel
#'
#' @description Wrapper around ppl_run_pipe_dst1 (fit step) for furrr parallel calls
#' @param .sp_code Species SAFRING code
#' @param .year Year to run to the pipeline for
#' @param .spatial Whether a spatial model should be fit. Defaults to FALSE.
#' @param .config Config object from \link{configPreambOccu}
#'
#' @export
#' @keywords internal
#' @noRd
#' @example
#' \dontrun{}
pipe_prll_fit <- function(.sp_code, .year, .spatial = FALSE, .config){

    # Species name
    sp_name <- BIRDIE::barberspan %>%
        dplyr::filter(SppRef == .sp_code) %>%
        dplyr::mutate(name = paste(Common_species, Common_group)) %>%
        dplyr::mutate(name = gsub(" NA|NA ", "", name)) %>% # in case there are NAs in species or group
        dplyr::pull(name) %>%
        unique()

    # Pipeline module 1
    out_dst1 <- ppl_run_pipe_dst1(sp_code = .sp_code,
                                  sp_name = sp_name,
                                  year = .year,
                                  config = .config,
                                  steps = c("data", "fit", "diagnose", "summary"),
                                  force_gee_dwld = FALSE,
                                  force_abap_dwld = FALSE,
                                  save_occu_data = TRUE,
                                  overwrite_occu_data = c("site", "visit", "det"),
                                  scale_vars_occur = list(visit = NULL,
                                                          site = c("dist_coast", "prcp", "tdiff", "ndvi", "watext", "watrec")),
                                  spatial = .spatial,
                                  print_fitting = FALSE,
                                  verbose = TRUE,
                                  monitor = FALSE)

    message(paste("Pipeline DST1 status =", out_dst1))

}
#'
#' Generate fit status messages
#'
#' @param .fit_out Fit status object generated by \code{\link{ppl_fit_occu_model}}
#' @param .year Year to run to the pipeline for
#' @param .sp_code Species SAFRING code
#' @param .config Config object from \link{configPreambOccu}
#'
#' @export
#' @keywords internal
#' @noRd
#' @example
#' \dontrun{}
logFitStatus <- function(.fit_out, .year, .sp_code, .config){

    if(is.numeric(.fit_out)){ # this immediately flags a problem

        txt <- dplyr::case_when(.fit_out == 1 ~ paste0("no_detections_", .year,"_", .sp_code, ".txt"),
                                .fit_out == 2 ~ paste0("less_than_5_pentads_", .year,"_", .sp_code, ".txt"),
                                .fit_out == 3 ~ paste0("model_fit_failed_", .year,"_", .sp_code, ".txt"))

        conv_file <- file.path(.config$out_dir, "reports", txt)
        sink(conv_file)
        print(gsub(".txt", "", txt))
        sink()
        message(gsub(".txt", "", txt)) # to console

        out <- .fit_out

    } else {
        out <- 0
    }

    return(out)

}

#' Create pipeline event log
#'
#' @description This function will create a customized log entry for a log file
#' that records the activity of the pipeline. More precisely, it will record the
#' time, species and outcome of data preparation, model fitting, diagnostics and
#' preparation.
#' @param config A list with pipeline configuration parameters.
#' See \code{\link{configPreambOccu}} and \code{\link{configPreambAbu}}.
#' @param logfile Optional. A character string with the path to the file that
#' should be updated. If NULL (default) a new log file will be created.
#' @param date_time Optional. A character string with the log date. If NULL (default)
#' the time given by \code{\link{Sys.time()}}, formatted as SAST will be used.
#' @param species SAFRING code of the species the log corresponds to.
#' @param model Type of model being processed. Either "occ" or "ssm".
#' @param data Data preparation status. Defaults to NA.
#' @param fit model fitting status. Defaults to NA.
#' @param diagnose Model diagnostics status. Defaults to NA.
#' @param summary Model summary status. Defaults to NA.
#' @param notes Any additional comments. Defaults to NA.
#' @param full_log Optionally, we can pass a full vector log, with all the above
#' elements. In this case, all other arguments but \code{config} and \code{logfile}
#' will be ignored.
#'
#' @return A .csv will be saved on the reports directory. The location of this
#' directory is configured in the configuration object passed as \code{config} at
#' \code{config$output_dir}.
#' @export
#' @keywords internal
#' @noRd
#' @example
#' \dontrun{}
createLog <- function(config, logfile = NULL, date_time = NULL, species = NULL,
                      model = NULL, data = NA, fit = NA, diagnose = NA,
                      summary = NA, package = NA, notes = "", full_log = NULL){

    s <- Sys.time()
    attr(s,"tzone") <- "Africa/Johannesburg"
    today <- format(s, format = "%Y-%m-%d")

    if(is.null(date_time)){
        date_time <- format(s)
    }

    if(is.null(full_log)){
        new_log <- c(date_time, species, model, data, fit, diagnose, summary, package, notes)
    } else {
        new_log <- full_log
    }


    if(is.null(logfile)){
        logfile <- file.path(config$out_dir, "reports", paste0("pipe_log_", today,".csv"))
        log <- data.frame(date_time = character(),
                          species = numeric(),
                          model = character(),
                          data = numeric(),
                          fit = numeric(),
                          diagnose = numeric(),
                          summary = numeric(),
                          package = character(),
                          notes = character())
        utils::write.csv(log, logfile, row.names = FALSE)
        message(paste("log file created:", logfile))
    }

    log <- utils::read.csv(logfile)
    new_row <- nrow(log) + 1

    log[new_row, ] <- new_log

    utils::write.csv(log, logfile, row.names = FALSE)

}

