#'
#' Fit occupancy models in parallel
#'
#' @description Wrapper around ppl_run_pipe_dst1 (fit step) for furrr parallel calls
#' @param .sp_code Species SAFRING code
#' @param .year Year to run to the pipeline for
#' @param .spatial Whether a spatial model should be fit. Defaults to FALSE.
#' @param .config Config object from \link{configPreambOccu}
#'
#' @export
#' @keywords internal
#' @noRd
#' @example
#' \dontrun{}
pipe_prll_fit <- function(.sp_code, .year, .spatial = FALSE, .config){

    # Species name
    sp_name <- BIRDIE::barberspan %>%
        dplyr::filter(SppRef == .sp_code) %>%
        dplyr::mutate(name = paste(Common_species, Common_group)) %>%
        dplyr::mutate(name = gsub(" NA|NA ", "", name)) %>% # in case there are NAs in species or group
        dplyr::pull(name) %>%
        unique()

    # Pipeline module 1
    out_dst1 <- ppl_run_pipe_dst1(sp_code = .sp_code,
                                  sp_name = sp_name,
                                  year = .year,
                                  config = .config,
                                  steps = c("fit"),
                                  force_gee_dwld = FALSE,
                                  monitor_gee = TRUE,
                                  force_site_visit = TRUE,
                                  force_abap_dwld = FALSE,
                                  spatial = .spatial,
                                  print_fitting = TRUE)

    message(paste("Pipeline DST1 status =", out_dst1))

}


#'
#' Generate fit status messages
#'
#' @param .fit_out Fit status object generated by \code{\link{ppl_fit_occu_model}}
#' @param .year Year to run to the pipeline for
#' @param .sp_code Species SAFRING code
#' @param .config Config object from \link{configPreambOccu}
#'
#' @export
#' @keywords internal
#' @noRd
#' @example
#' \dontrun{}
logFitStatus <- function(.fit_out, .year, .sp_code, .config){

    if(is.numeric(.fit_out)){ # this immediately flags a problem

        min_pentads <- 2*length(.config$occ_mod)

        txt <- dplyr::case_when(.fit_out == 1 ~ paste0("no_detections_", .year,"_", .sp_code, ".txt"),
                                .fit_out == 2 ~ paste0("less_than_", min_pentads, "_pentads_", .year,"_", .sp_code, ".txt"),
                                .fit_out == 3 ~ paste0("model_fit_failed_", .year,"_", .sp_code, ".txt"))

        conv_file <- file.path(.config$out_dir, "reports", txt)
        sink(conv_file)
        print(gsub(".txt", "", txt))
        sink()
        message(gsub(".txt", "", txt)) # to console

        out <- .fit_out

    } else {
        out <- 0
    }

    return(out)

}

#' Create pipeline event log
#'
#' @description This function will create a customized log entry for a log file
#' that records the activity of the pipeline. More precisely, it will record the
#' time, species and outcome of data preparation, model fitting, diagnostics and
#' preparation.
#' @param config A list with pipeline configuration parameters.
#' See \code{\link{configPreambOccu}} and \code{\link{configPreambAbu}}.
#' @param log_file Optional. A character string with the path to the file that
#' should be updated. If NULL (default) a new log file will be created.
#' @param date_time Optional. A character string with the log date. If NULL (default)
#' the time given by \code{\link{Sys.time()}}, formatted as SAST will be used.
#' @param species SAFRING code of the species the log corresponds to.
#' @param model Type of model being processed. Either "occ" or "ssm".
#' @param year Year the model is fit for.
#' @param data Data preparation status. Defaults to NA.
#' @param fit model fitting status. Defaults to NA.
#' @param diagnose Model diagnostics status. Defaults to NA.
#' @param summary Model summary status. Defaults to NA.
#' @param notes Any additional comments. Defaults to NA.
#' @param full_log Optionally, we can pass a full vector log, with all the above
#' elements. In this case, all other arguments but \code{config} and \code{logfile}
#' will be ignored.
#'
#' @return A .csv will be saved on the reports directory. The location of this
#' directory is configured in the configuration object passed as \code{config} at
#' \code{config$output_dir}.
#' @export
#' @keywords internal
#' @noRd
#' @example
#' \dontrun{}
createLog <- function(config, log_file = NULL, date_time = NULL, species = NULL,
                      model = NULL, year = NA, data = NA, fit = NA, diagnose = NA,
                      summary = NA, package = NA, notes = "", full_log = NULL){

    s <- Sys.time()
    attr(s,"tzone") <- "Africa/Johannesburg"
    today <- format(s, format = "%Y-%m-%d")

    if(is.null(date_time)){
        date_time <- format(s)
    }

    if(is.null(full_log)){
        new_log <- c(date_time, species, model, year, data, fit, diagnose, summary, package, notes)
    } else {
        new_log <- full_log
    }


    if(is.null(log_file)){
        log_file <- file.path(config$out_dir, "reports", paste0("pipe_log_", config$module, "_", today,".csv"))
        log <- data.frame(date_time = character(),
                          species = numeric(),
                          model = character(),
                          year = numeric(),
                          data = numeric(),
                          fit = numeric(),
                          diagnose = numeric(),
                          summary = numeric(),
                          package = character(),
                          notes = character())
        utils::write.csv(log, log_file, row.names = FALSE)
        message(paste("log file created:", log_file))
    }

    log <- utils::read.csv(log_file)
    new_row <- nrow(log) + 1

    log[new_row, ] <- new_log

    utils::write.csv(log, log_file, row.names = FALSE)

}


#' Create a combined file for export to data mart
#'
#' @param config A list with pipeline configuration parameters.
#' See \link{configPreambJAGS} and \link{configPreambOccuR}
#' @param type A character string with three options: "abu", for abundance estimates files,
#' "dst" for occupancy estimates files, or "indtr_dst" for distribution indicator files.
#'
#' @return It will create a file in config$out_dir combining all files of the selected
#' type of all species and years in config$years.
#' @export
#'
#' @examples
createCombinedExportFile <- function(config, type = c("abu", "dst", "indtr_dst")){

    if(type == "abu"){

        abu_out <- data.frame()

        for(i in 1:length(config$species)){

            sp_code <- config$species[i]

            abu_file <- file.path(config$out_dir, sp_code, paste0("ssm_pred_", config$years_ch, "_", sp_code, "_all.csv"))

            if(file.exists(abu_file)){
                new_abu <- utils::read.csv(abu_file)
                new_abu <- round(new_abu, 3)
                abu_out <- rbind(abu_out, new_abu)
            } else {
                abu_out <- abu_out
            }

        }

        utils::write.csv(abu_out, file.path(config$out_dir, "export", paste0("ssm_pred_", config$years_ch, "_all_all.csv")),
                         row.names = FALSE)
    }

    if(type == "dst"){

        dst_out <- data.frame()

        for(i in 1:length(config$species)){

            sp_code <- config$species[i]

            for(y in 1:length(config$years)){

                yr <- substring(as.character(config$years[y]), 3, 4)
                dst_file <- file.path(config$out_dir, sp_code, paste0("occur_pred_", yr, "_", sp_code, ".csv"))

                if(file.exists(dst_file)){
                    new_dst <- utils::read.csv(dst_file)
                    new_dst <- round(new_dst, 3)
                    dst_out <- rbind(dst_out, new_dst)
                } else {
                    dst_out <- dst_out
                }

            }

        }

        utils::write.csv(dst_out, file.path(config$out_dir, "export", paste0("occur_pred_", config$years_ch, "_all.csv")),
                         row.names = FALSE)
    }

    if(type == "indtr_dst"){

        dst_out <- data.frame()

        for(i in 1:length(config$species)){

            sp_code <- config$species[i]

            dst_file <- file.path(config$out_dir, sp_code, paste0("indtr_dst_", sp_code, "_", config$year, ".csv"))

            if(file.exists(dst_file)){
                new_dst <- utils::read.csv(dst_file)
                new_dst <- round(new_dst, 3)
                dst_out <- rbind(dst_out, utils::read.csv(dst_file))
            } else {
                dst_out <- dst_out
            }

        }

        utils::write.csv(dst_out, file.path(config$out_dir, "export", paste0("indtr_dst_all_", config$years_ch, ".csv")),
                         row.names = FALSE)
    }


}


#' Set a standard path for a pipeline output file associated with a species
#'
#' @description The datapipeline produces many output files. This function
#' creates an standard output file path for those files that are associated with
#' a particular species. There might be instances where we need name that
#'  deviates from the standard. We need to handle these exceptions
#' case by case. Those files that are not associated with a particular species
#' follow different standards.
#' @param prefix A character string with the prefix that will appear at the
#' beginning of the name. This is what distinguishes files within the species
#' directory.
#' @param config A list with pipeline configuration parameters.
#' See \link{configPreambJAGS} and \link{configPreambOccuR}.
#' @param sp_code SAFRING reference number of the species we want to analyze.
#' @param ext The extension of the output file. Note that we must add the
#' trailing '.' to the extension.
#'
#' @return A character string with the path to/for a pipeline output file
#' @export
#'
#' @examples
#' \dontrun{
#' config <- configPreambJAGS(2017, server = FALSE)
#' sp_code <- 4
#'
#' # Set a file path for a state-space model output
#' setSpOutFilePath("ssm_fit", config, sp_code, ".rds)
#'
#' # Set a file path for model-ready data
#' setSpOutFilePath("model_data", config, sp_code, ".csv)
#' }
setSpOutFilePath <- function(prefix, config, sp_code, ext){
    file.path(config$out_dir, sp_code, paste0(prefix, "_", config$years_ch, "_", sp_code, ext))
}

